#!/bin/bash

echo "======================================"
echo "GitHub Wiki 자동 생성 스크립트"
echo "======================================"
echo ""

REPO="gdtknight/miniRT_final"
WIKI_URL="https://github.com/$REPO/wiki"

echo "1. 브라우저에서 다음 URL을 열어주세요:"
echo "   $WIKI_URL"
echo ""
echo "2. 'Create the first page' 버튼을 클릭하세요"
echo ""
echo "3. 아무 내용(예: 'Initial page')을 입력하고 Save 클릭"
echo ""
echo "4. 저장 후 아래 명령어를 실행하세요:"
echo ""
echo "   cd /tmp"
echo "   git clone git@github.com:$REPO.wiki.git"
echo "   cd miniRT_final.wiki"
echo "   cp /tmp/miniRT_wiki/*.md ."
echo "   git add ."
echo "   git commit -m 'Add comprehensive Korean documentation'"
echo "   git push origin master"
echo ""
echo "======================================"
echo ""
echo "Wiki 파일 준비 상태:"
ls -lh /tmp/miniRT_wiki/*.md 2>/dev/null | awk '{print "  " $9}' || echo "  (파일을 다시 생성해야 합니다)"
echo ""
echo "자세한 내용은 WIKI_SETUP.md 를 참고하세요"
